// Mocks generated by Mockito 5.4.6 from annotations
// in meal_of_record/test/services/try_auto_backup_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:meal_of_record/services/backup_config_service.dart' as _i5;
import 'package:meal_of_record/services/nas_backup_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NasBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNasBackupService extends _i1.Mock implements _i2.NasBackupService {
  MockNasBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> uploadBackup(_i4.File? zipFile, {int? retentionCount = 7}) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadBackup,
              [zipFile],
              {#retentionCount: retentionCount},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i2.NasBackupFile>> listBackups() =>
      (super.noSuchMethod(
            Invocation.method(#listBackups, []),
            returnValue: _i3.Future<List<_i2.NasBackupFile>>.value(
              <_i2.NasBackupFile>[],
            ),
          )
          as _i3.Future<List<_i2.NasBackupFile>>);

  @override
  _i3.Future<_i4.File?> downloadBackup(String? href) =>
      (super.noSuchMethod(
            Invocation.method(#downloadBackup, [href]),
            returnValue: _i3.Future<_i4.File?>.value(),
          )
          as _i3.Future<_i4.File?>);

  @override
  List<_i2.NasBackupFile> parsePropfindResponse(String? xmlBody) =>
      (super.noSuchMethod(
            Invocation.method(#parsePropfindResponse, [xmlBody]),
            returnValue: <_i2.NasBackupFile>[],
          )
          as List<_i2.NasBackupFile>);
}

/// A class which mocks [BackupConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupConfigService extends _i1.Mock
    implements _i5.BackupConfigService {
  MockBackupConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set secureStorage(_i6.FlutterSecureStorage? storage) => super.noSuchMethod(
    Invocation.setter(#secureStorage, storage),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> setAutoBackupEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoBackupEnabled, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isAutoBackupEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isAutoBackupEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setRetentionCount(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setRetentionCount, [count]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getRetentionCount() =>
      (super.noSuchMethod(
            Invocation.method(#getRetentionCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> markDirty() =>
      (super.noSuchMethod(
            Invocation.method(#markDirty, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearDirty() =>
      (super.noSuchMethod(
            Invocation.method(#clearDirty, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isDirty() =>
      (super.noSuchMethod(
            Invocation.method(#isDirty, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updateLastBackupTime() =>
      (super.noSuchMethod(
            Invocation.method(#updateLastBackupTime, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastBackupTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastBackupTime, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> setNasHost(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#setNasHost, [host]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getNasHost() =>
      (super.noSuchMethod(
            Invocation.method(#getNasHost, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setNasPort(int? port) =>
      (super.noSuchMethod(
            Invocation.method(#setNasPort, [port]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int?> getNasPort() =>
      (super.noSuchMethod(
            Invocation.method(#getNasPort, []),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<void> setNasPath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setNasPath, [path]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getNasPath() =>
      (super.noSuchMethod(
            Invocation.method(#getNasPath, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setNasUseHttps(bool? useHttps) =>
      (super.noSuchMethod(
            Invocation.method(#setNasUseHttps, [useHttps]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getNasUseHttps() =>
      (super.noSuchMethod(
            Invocation.method(#getNasUseHttps, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setNasAllowSelfSigned(bool? allow) =>
      (super.noSuchMethod(
            Invocation.method(#setNasAllowSelfSigned, [allow]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getNasAllowSelfSigned() =>
      (super.noSuchMethod(
            Invocation.method(#getNasAllowSelfSigned, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> recordBackupFailure() =>
      (super.noSuchMethod(
            Invocation.method(#recordBackupFailure, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> recordBackupSuccess() =>
      (super.noSuchMethod(
            Invocation.method(#recordBackupSuccess, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getConsecutiveFailures() =>
      (super.noSuchMethod(
            Invocation.method(#getConsecutiveFailures, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> saveNasCredentials(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#saveNasCredentials, [username, password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<(String?, String?)> getNasCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#getNasCredentials, []),
            returnValue: _i3.Future<(String?, String?)>.value((null, null)),
          )
          as _i3.Future<(String?, String?)>);

  @override
  _i3.Future<void> clearNasCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearNasCredentials, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isNasConfigured() =>
      (super.noSuchMethod(
            Invocation.method(#isNasConfigured, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
