// Mocks generated by Mockito 5.4.6 from annotations
// in meal_of_record/test/screens/clear_on_leave_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i12;

import 'package:flutter/material.dart' as _i14;
import 'package:flutter/services.dart' as _i13;
import 'package:meal_of_record/models/category.dart' as _i17;
import 'package:meal_of_record/models/food.dart' as _i8;
import 'package:meal_of_record/models/goal_settings.dart' as _i5;
import 'package:meal_of_record/models/macro_goals.dart' as _i6;
import 'package:meal_of_record/models/recipe.dart' as _i18;
import 'package:meal_of_record/models/recipe_item.dart' as _i16;
import 'package:meal_of_record/models/weight.dart' as _i20;
import 'package:meal_of_record/providers/goals_provider.dart' as _i11;
import 'package:meal_of_record/providers/recipe_provider.dart' as _i15;
import 'package:meal_of_record/providers/weight_provider.dart' as _i19;
import 'package:meal_of_record/services/database_service.dart' as _i2;
import 'package:meal_of_record/services/food_sorting_service.dart' as _i4;
import 'package:meal_of_record/services/open_food_facts_service.dart' as _i3;
import 'package:meal_of_record/services/search_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffApiService_1 extends _i1.SmartFake implements _i3.OffApiService {
  _FakeOffApiService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodSortingService_2 extends _i1.SmartFake
    implements _i4.FoodSortingService {
  _FakeFoodSortingService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalSettings_3 extends _i1.SmartFake implements _i5.GoalSettings {
  _FakeGoalSettings_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacroGoals_4 extends _i1.SmartFake implements _i6.MacroGoals {
  _FakeMacroGoals_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OffApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffApiService extends _i1.Mock implements _i3.OffApiService {
  MockOffApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Food?> fetchFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFoodByBarcode, [barcode]),
            returnValue: _i7.Future<_i8.Food?>.value(),
          )
          as _i7.Future<_i8.Food?>);

  @override
  _i7.Future<List<_i8.Food>> searchFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFoodsByName, [query]),
            returnValue: _i7.Future<List<_i8.Food>>.value(<_i8.Food>[]),
          )
          as _i7.Future<List<_i8.Food>>);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i9.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i3.OffApiService get offApiService =>
      (super.noSuchMethod(
            Invocation.getter(#offApiService),
            returnValue: _FakeOffApiService_1(
              this,
              Invocation.getter(#offApiService),
            ),
          )
          as _i3.OffApiService);

  @override
  String Function(String) get emojiForFoodName =>
      (super.noSuchMethod(
            Invocation.getter(#emojiForFoodName),
            returnValue: (String __p0) => _i10.dummyValue<String>(
              this,
              Invocation.getter(#emojiForFoodName),
            ),
          )
          as String Function(String));

  @override
  _i4.FoodSortingService get sortingService =>
      (super.noSuchMethod(
            Invocation.getter(#sortingService),
            returnValue: _FakeFoodSortingService_2(
              this,
              Invocation.getter(#sortingService),
            ),
          )
          as _i4.FoodSortingService);

  @override
  _i7.Future<List<_i8.Food>> searchLocal(String? query, {int? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchLocal, [query], {#categoryId: categoryId}),
            returnValue: _i7.Future<List<_i8.Food>>.value(<_i8.Food>[]),
          )
          as _i7.Future<List<_i8.Food>>);

  @override
  _i7.Future<List<_i8.Food>> searchOff(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchOff, [query]),
            returnValue: _i7.Future<List<_i8.Food>>.value(<_i8.Food>[]),
          )
          as _i7.Future<List<_i8.Food>>);

  @override
  _i7.Future<List<_i8.Food>> getAllRecipesAsFoods({int? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecipesAsFoods, [], {
              #categoryId: categoryId,
            }),
            returnValue: _i7.Future<List<_i8.Food>>.value(<_i8.Food>[]),
          )
          as _i7.Future<List<_i8.Food>>);

  @override
  _i7.Future<List<_i8.Food>> searchRecipesOnly(
    String? query, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchRecipesOnly,
              [query],
              {#categoryId: categoryId},
            ),
            returnValue: _i7.Future<List<_i8.Food>>.value(<_i8.Food>[]),
          )
          as _i7.Future<List<_i8.Food>>);
}

/// A class which mocks [GoalsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsProvider extends _i1.Mock implements _i11.GoalsProvider {
  MockGoalsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.GoalSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeGoalSettings_3(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i5.GoalSettings);

  @override
  _i6.MacroGoals get currentGoals =>
      (super.noSuchMethod(
            Invocation.getter(#currentGoals),
            returnValue: _FakeMacroGoals_4(
              this,
              Invocation.getter(#currentGoals),
            ),
          )
          as _i6.MacroGoals);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get showUpdateNotification =>
      (super.noSuchMethod(
            Invocation.getter(#showUpdateNotification),
            returnValue: false,
          )
          as bool);

  @override
  bool get isGoalsSet =>
      (super.noSuchMethod(Invocation.getter(#isGoalsSet), returnValue: false)
          as bool);

  @override
  bool get hasSeenWelcome =>
      (super.noSuchMethod(
            Invocation.getter(#hasSeenWelcome),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAppLifecycleState(_i12.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void dismissNotification() => super.noSuchMethod(
    Invocation.method(#dismissNotification, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> saveSettings(
    _i5.GoalSettings? newSettings, {
    bool? isInitialSetup = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSettings,
              [newSettings],
              {#isInitialSetup: isInitialSetup},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markWelcomeSeen() =>
      (super.noSuchMethod(
            Invocation.method(#markWelcomeSeen, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> checkWeeklyUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#checkWeeklyUpdate, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> recalculateTargets({bool? isInitialSetup = false}) =>
      (super.noSuchMethod(
            Invocation.method(#recalculateTargets, [], {
              #isInitialSetup: isInitialSetup,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  bool handleStartBackGesture(_i13.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i13.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> didPushRouteInformation(
    _i14.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i12.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i12.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i12.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i7.Future<_i12.AppExitResponse>.value(
              _i12.AppExitResponse.exit,
            ),
          )
          as _i7.Future<_i12.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RecipeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeProvider extends _i1.Mock implements _i15.RecipeProvider {
  MockRecipeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: 0) as int);

  @override
  bool get isLogged =>
      (super.noSuchMethod(Invocation.getter(#isLogged), returnValue: false)
          as bool);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  double get servingsCreated =>
      (super.noSuchMethod(Invocation.getter(#servingsCreated), returnValue: 0.0)
          as double);

  @override
  String get portionName =>
      (super.noSuchMethod(
            Invocation.getter(#portionName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#portionName),
            ),
          )
          as String);

  @override
  String get notes =>
      (super.noSuchMethod(
            Invocation.getter(#notes),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#notes),
            ),
          )
          as String);

  @override
  bool get isTemplate =>
      (super.noSuchMethod(Invocation.getter(#isTemplate), returnValue: false)
          as bool);

  @override
  String get emoji =>
      (super.noSuchMethod(
            Invocation.getter(#emoji),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#emoji),
            ),
          )
          as String);

  @override
  List<_i16.RecipeItem> get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: <_i16.RecipeItem>[],
          )
          as List<_i16.RecipeItem>);

  @override
  List<_i17.Category> get selectedCategories =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCategories),
            returnValue: <_i17.Category>[],
          )
          as List<_i17.Category>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get ingredientsChanged =>
      (super.noSuchMethod(
            Invocation.getter(#ingredientsChanged),
            returnValue: false,
          )
          as bool);

  @override
  double get totalCalories =>
      (super.noSuchMethod(Invocation.getter(#totalCalories), returnValue: 0.0)
          as double);

  @override
  double get totalProtein =>
      (super.noSuchMethod(Invocation.getter(#totalProtein), returnValue: 0.0)
          as double);

  @override
  double get totalFat =>
      (super.noSuchMethod(Invocation.getter(#totalFat), returnValue: 0.0)
          as double);

  @override
  double get totalCarbs =>
      (super.noSuchMethod(Invocation.getter(#totalCarbs), returnValue: 0.0)
          as double);

  @override
  double get totalFiber =>
      (super.noSuchMethod(Invocation.getter(#totalFiber), returnValue: 0.0)
          as double);

  @override
  double get caloriesPerPortion =>
      (super.noSuchMethod(
            Invocation.getter(#caloriesPerPortion),
            returnValue: 0.0,
          )
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setName(String? val) => super.noSuchMethod(
    Invocation.method(#setName, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setServingsCreated(double? val) => super.noSuchMethod(
    Invocation.method(#setServingsCreated, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setFinalWeightGrams(double? val) => super.noSuchMethod(
    Invocation.method(#setFinalWeightGrams, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setPortionName(String? val) => super.noSuchMethod(
    Invocation.method(#setPortionName, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setNotes(String? val) => super.noSuchMethod(
    Invocation.method(#setNotes, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setIsTemplate(bool? val) => super.noSuchMethod(
    Invocation.method(#setIsTemplate, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setEmoji(String? val) => super.noSuchMethod(
    Invocation.method(#setEmoji, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setThumbnail(String? val) => super.noSuchMethod(
    Invocation.method(#setThumbnail, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void addItem(_i16.RecipeItem? item) => super.noSuchMethod(
    Invocation.method(#addItem, [item]),
    returnValueForMissingStub: null,
  );

  @override
  void removeItem(int? index) => super.noSuchMethod(
    Invocation.method(#removeItem, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void updateItem(int? index, _i16.RecipeItem? newItem) => super.noSuchMethod(
    Invocation.method(#updateItem, [index, newItem]),
    returnValueForMissingStub: null,
  );

  @override
  void reorderItem(int? oldIndex, int? newIndex) => super.noSuchMethod(
    Invocation.method(#reorderItem, [oldIndex, newIndex]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleCategory(_i17.Category? category) => super.noSuchMethod(
    Invocation.method(#toggleCategory, [category]),
    returnValueForMissingStub: null,
  );

  @override
  void loadFromRecipe(_i18.Recipe? recipe, {bool? isLogged = false}) =>
      super.noSuchMethod(
        Invocation.method(#loadFromRecipe, [recipe], {#isLogged: isLogged}),
        returnValueForMissingStub: null,
      );

  @override
  void prepareCopy(_i18.Recipe? recipe) => super.noSuchMethod(
    Invocation.method(#prepareCopy, [recipe]),
    returnValueForMissingStub: null,
  );

  @override
  void prepareVersion(_i18.Recipe? recipe) => super.noSuchMethod(
    Invocation.method(#prepareVersion, [recipe]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> saveRecipe() =>
      (super.noSuchMethod(
            Invocation.method(#saveRecipe, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<String> exportRecipe(_i18.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#exportRecipe, [recipe]),
            returnValue: _i7.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#exportRecipe, [recipe]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<int?> importRecipe(String? jsonContent) =>
      (super.noSuchMethod(
            Invocation.method(#importRecipe, [jsonContent]),
            returnValue: _i7.Future<int?>.value(),
          )
          as _i7.Future<int?>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WeightProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightProvider extends _i1.Mock implements _i19.WeightProvider {
  MockWeightProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i20.Weight> get weights =>
      (super.noSuchMethod(
            Invocation.getter(#weights),
            returnValue: <_i20.Weight>[],
          )
          as List<_i20.Weight>);

  @override
  List<_i20.Weight> get recentWeights =>
      (super.noSuchMethod(
            Invocation.getter(#recentWeights),
            returnValue: <_i20.Weight>[],
          )
          as List<_i20.Weight>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasWeightToday =>
      (super.noSuchMethod(
            Invocation.getter(#hasWeightToday),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i20.Weight? getWeightForDate(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(#getWeightForDate, [date]))
          as _i20.Weight?);

  @override
  _i7.Future<void> loadWeights(DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
            Invocation.method(#loadWeights, [start, end]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveWeight(double? value, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#saveWeight, [value, date]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteWeight(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWeight, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
